version: '3'
services:
    chinadns:
        build: .
        image: xyzrlee/chinadns
        restart: unless-stopped
        ports:
            - "5353:53/udp"
        volumes:
            - .:/conf:ro
        command:
            - "-v"
            - "-c /conf/chnroute.txt"
